site_name: Bioinformatics and computational approaches in Microbiology
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Project 1: project1.md
    - Project 2: 
      - Description: project2.md
      - Preparation: project2/Project2_Preparation.md
      - Overview: project2/Project2_Overview.md
      - Project 2A: project2/Project-2A.md
      - Project 2B: project2/Project-2B.md
      - Project 2C: project2/project-2C.md
    - Project 3:
      - Description: project3.md
      - Preparation: project3/Prepare-before-start-of-the-course.md
    - Project 4: 
      - Description: project4.md
      - Project 4A: project4/project4a.md
      - Project 4B: project4/project4b.md
      - Software: project4/software.md
      - Project timeline: project4/timeline.md

theme:
  name: material
  icon: 
    logo: material/bacteria
  favicon: assets/images/bacteria.png
  palette:
    primary: grey
    accent: red


# Repository
repo_name: sib-swiss/spring_school_bioinformatics_microbiology
repo_url: https://github.com/sib-swiss/spring_school_bioinformatics_microbiology

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra_css:
#   - stylesheets/extra.css
